[workspace]
resolver = "2"
members = [
  "crates/wasm-bridge",
  "crates/wasm-bridge-js",
  "crates/wasm-bridge-wasi",
  "crates/wasm-bridge-macros",
  "crates/wasm-bridge-bindgen",

  "examples/wit_components/",
  "examples/wit_components/guest/*/",

  "examples/wasi_components/",
  "examples/wasi_components/guest/*",
]

exclude = [
  "tests/",
  "jco/"
]

[workspace.package]
version = "0.2.2"
edition = "2021"
repository = "https://github.com/kajacx/wasm-bridge"
license = "MIT"
keywords = ["WASM", "wasmtime", "web"]
categories = ["wasm", "web-programming"]
